In [11]:
import pandas as pd
import numpy as np
import scipy.stats as stats
import sklearn

In [25]:
boston_houseprice_data = pd.read_csv("data/housing.data",header=0,index_col=None,sep='\s+')

In [26]:
boston_houseprice_data.head()

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0  0.00632  18.0   2.31     0  0.538  6.575  65.2  4.0900    1  296.0   
1  0.02731   0.0   7.07     0  0.469  6.421  78.9  4.9671    2  242.0   
2  0.02729   0.0   7.07     0  0.469  7.185  61.1  4.9671    2  242.0   
3  0.03237   0.0   2.18     0  0.458  6.998  45.8  6.0622    3  222.0   
4  0.06905   0.0   2.18     0  0.458  7.147  54.2  6.0622    3  222.0   

   PTRATIO       B  LSTAT  MEDV  
0     15.3  396.90   4.98  24.0  
1     17.8  396.90   9.14  21.6  
2     17.8  392.83   4.03  34.7  
3     18.7  394.63   2.94  33.4  
4     18.7  396.90   5.33  36.2

In [36]:
data_sample = boston_houseprice_data.iloc[:, :-1].values
data_label = boston_houseprice_data.iloc[:, -1].values
bias = np.ones((data_sample.shape[0], 1))
data_sample = np.concatenate((data_sample,bias), axis=1)

In [106]:
mean =data_sample.mean(axis=0)

In [110]:
mean

array([3.61352356e+00, 1.13636364e+01, 1.11367787e+01, 6.91699605e-02,
       5.54695059e-01, 6.28463439e+00, 6.85749012e+01, 3.79504269e+00,
       9.54940711e+00, 4.08237154e+02, 1.84555336e+01, 3.56674032e+02,
       1.26530632e+01, 1.00000000e+00])

In [107]:
std = data_sample.std(axis=0)

In [112]:
(data_sample-mean)/std

C:\Users\admin\Anaconda3\envs\python35\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([[-0.41978194,  0.28482986, -1.2879095 , ...,  0.44105193,
        -1.0755623 ,         nan],
       [-0.41733926, -0.48772236, -0.59338101, ...,  0.44105193,
        -0.49243937,         nan],
       [-0.41734159, -0.48772236, -0.59338101, ...,  0.39642699,
        -1.2087274 ,         nan],
       ...,
       [-0.41344658, -0.48772236,  0.11573841, ...,  0.44105193,
        -0.98304761,         nan],
       [-0.40776407, -0.48772236,  0.11573841, ...,  0.4032249 ,
        -0.86530163,         nan],
       [-0.41500016, -0.48772236,  0.11573841, ...,  0.44105193,
        -0.66905833,         nan]])

In [37]:
data_sample.shape[0]

506

In [38]:
data_sample

array([[6.3200e-03, 1.8000e+01, 2.3100e+00, ..., 3.9690e+02, 4.9800e+00,
        1.0000e+00],
       [2.7310e-02, 0.0000e+00, 7.0700e+00, ..., 3.9690e+02, 9.1400e+00,
        1.0000e+00],
       [2.7290e-02, 0.0000e+00, 7.0700e+00, ..., 3.9283e+02, 4.0300e+00,
        1.0000e+00],
       ...,
       [6.0760e-02, 0.0000e+00, 1.1930e+01, ..., 3.9690e+02, 5.6400e+00,
        1.0000e+00],
       [1.0959e-01, 0.0000e+00, 1.1930e+01, ..., 3.9345e+02, 6.4800e+00,
        1.0000e+00],
       [4.7410e-02, 0.0000e+00, 1.1930e+01, ..., 3.9690e+02, 7.8800e+00,
        1.0000e+00]])

In [ ]:
boston_houseprice_data

In [12]:
data_length = data_label.shape[0]

In [14]:
train_data_length = int(data_length*0.8)

In [15]:
data_sample_train,data_sample_test = data_sample[:train_data_length], data_sample[train_data_length:]

In [16]:
data_label_train, data_label_test = data_label[:train_data_length], data_label[train_data_length:]

In [18]:
data_sample_train.shape

(404, 13)

In [ ]:
num_iterations = 1000
lr = 0.01
weight_decay = 0.001
train_batch_size = 16
test_batch_size = 10000

In [41]:
def xavier(num_neuron_inputs, num_neuron_outputs):
    temp1 =  np.sqrt(6) / np.sqrt(num_neuron_inputs+ num_neuron_outputs + 1)
    weights = stats.uniform.rvs(-temp1, 2 * temp1, (num_neuron_inputs, num_neuron_outputs))
    return weights

In [42]:
batch_size = 503

In [43]:
def forward(inputs, weights):
    outputs = inputs.dot(weights)
    return outputs

In [44]:
inputs = data_sample

In [45]:
weights_input_to_hidden = xavier(14,16)

In [46]:
outputs_input_to_hidden = forward(inputs, weights_input_to_hidden)

In [47]:
outputs_input_to_hidden

array([[  12.83131751, -100.7952357 , -108.446928  , ...,  -35.02088655,
          75.19296777,   -1.04916604],
       [  25.37854674,  -95.80084884, -120.18216868, ...,  -48.5360009 ,
          50.30858591,   14.1506134 ],
       [  28.69075407,  -99.95275788, -112.46967813, ...,  -40.30463334,
          47.15274312,   10.61881358],
       ...,
       [  15.20118079,  -94.28901388, -122.29905734, ...,  -48.89831461,
          59.55641024,    2.2523299 ],
       [  14.23263443,  -93.45917323, -120.63612914, ...,  -47.88426205,
          60.18498872,    0.54069848],
       [  17.01015503,  -95.58455139, -118.27478149, ...,  -44.88523424,
          59.40439202,   -1.42955128]])

In [48]:
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

In [49]:
output_hidden_to_output = sigmoid(outputs_input_to_hidden)

In [50]:
output_hidden_to_output

array([[9.99997324e-01, 1.67952059e-44, 7.98174025e-48, ...,
        6.17479041e-16, 1.00000000e+00, 2.59385276e-01],
       [1.00000000e+00, 2.47867728e-42, 6.39068361e-53, ...,
        8.33839828e-22, 1.00000000e+00, 9.99999285e-01],
       [1.00000000e+00, 3.90003766e-44, 1.42902362e-49, ...,
        3.13270965e-18, 1.00000000e+00, 9.99975549e-01],
       ...,
       [9.99999750e-01, 1.12409125e-41, 7.69474541e-54, ...,
        5.80405863e-22, 1.00000000e+00, 9.04851318e-01],
       [9.99999341e-01, 2.57748878e-41, 4.05877330e-53, ...,
        1.60003404e-21, 1.00000000e+00, 6.31974888e-01],
       [9.99999959e-01, 3.07720745e-42, 4.30442405e-52, ...,
        3.21063141e-20, 1.00000000e+00, 1.93168609e-01]])

In [51]:
output_hidden_to_output.shape

(506, 16)

In [53]:
bias_hidden_to_output = np.ones((output_hidden_to_output.shape[0], 1))
ac1_output = np.concatenate((output_hidden_to_output, bias), axis=1)

In [55]:
weights_hidden_to_output = xavier(17,1)

In [56]:
output_hidden_to_output = forward(ac1_output, weights_hidden_to_output)

In [57]:
def identity(x):
    return x

In [58]:
predict = identity(output_hidden_to_output)

In [59]:
predict

array([[-0.72044781],
       [-1.09056908],
       [-1.09055722],
       [-1.09056942],
       [-1.09056943],
       [-1.09056943],
       [-0.59119304],
       [-0.69232122],
       [-0.71446935],
       [-0.70364278],
       [-0.70785129],
       [-0.60155034],
       [-0.590977  ],
       [-0.59090752],
       [-0.72143832],
       [-0.59086866],
       [-0.59091133],
       [-0.68698545],
       [-0.86753201],
       [-0.59395974],
       [-0.77199189],
       [-0.67214586],
       [-0.67940502],
       [-0.71582102],
       [-0.6962535 ],
       [-0.77777907],
       [-0.75865435],
       [-0.77777792],
       [-0.71501039],
       [-0.72650794],
       [-0.77767836],
       [-0.76404001],
       [-0.78837797],
       [-0.77764645],
       [-0.7802912 ],
       [-0.6003014 ],
       [-0.5908312 ],
       [-0.59083484],
       [-0.59082005],
       [-1.18519863],
       [-1.1852019 ],
       [-0.62990964],
       [-0.62495708],
       [-0.80890205],
       [-1.089476  ],
       [-1

In [78]:
label = data_label.reshape(-1,1)

In [79]:
label

array([[24. ],
       [21.6],
       [34.7],
       [33.4],
       [36.2],
       [28.7],
       [22.9],
       [27.1],
       [16.5],
       [18.9],
       [15. ],
       [18.9],
       [21.7],
       [20.4],
       [18.2],
       [19.9],
       [23.1],
       [17.5],
       [20.2],
       [18.2],
       [13.6],
       [19.6],
       [15.2],
       [14.5],
       [15.6],
       [13.9],
       [16.6],
       [14.8],
       [18.4],
       [21. ],
       [12.7],
       [14.5],
       [13.2],
       [13.1],
       [13.5],
       [18.9],
       [20. ],
       [21. ],
       [24.7],
       [30.8],
       [34.9],
       [26.6],
       [25.3],
       [24.7],
       [21.2],
       [19.3],
       [20. ],
       [16.6],
       [14.4],
       [19.4],
       [19.7],
       [20.5],
       [25. ],
       [23.4],
       [18.9],
       [35.4],
       [24.7],
       [31.6],
       [23.3],
       [19.6],
       [18.7],
       [16. ],
       [22.2],
       [25. ],
       [33. ],
       [23.5],
       [19

In [67]:
predict[:2]

array([[-0.72044781],
       [-1.09056908]])

In [68]:
label[:2]

array([24. , 21.6])

In [76]:
label[:2].reshape(-1,1)-predict[:2]

array([[24.72044781],
       [22.69056908]])

In [75]:
np.square(label[:2].reshape(-1,1)-predict[:2])

array([[611.10053978],
       [514.86192507]])

In [77]:
np.sum(np.square(label[:2].reshape(-1,1)-predict[:2]),1)

array([611.10053978, 514.86192507])

In [80]:
def identity_with_mse_loss(predict, label):
    tmp1 = np.sum(np.square(label-predict),1)
    loss = np.mean(tmp1)
    return loss

In [81]:
identity_with_mse_loss(predict,label)

635.7892313485684

In [82]:
def der_identity_with_mse_loss(predict, label):
    gradient = predict-label
    return gradient

In [83]:
grad_outputs = der_identity_with_mse_loss(predict,label)

In [84]:
grad_outputs

array([[-24.72044781],
       [-22.69056908],
       [-35.79055722],
       [-34.49056942],
       [-37.29056943],
       [-29.79056943],
       [-23.49119304],
       [-27.79232122],
       [-17.21446935],
       [-19.60364278],
       [-15.70785129],
       [-19.50155034],
       [-22.290977  ],
       [-20.99090752],
       [-18.92143832],
       [-20.49086866],
       [-23.69091133],
       [-18.18698545],
       [-21.06753201],
       [-18.79395974],
       [-14.37199189],
       [-20.27214586],
       [-15.87940502],
       [-15.21582102],
       [-16.2962535 ],
       [-14.67777907],
       [-17.35865435],
       [-15.57777792],
       [-19.11501039],
       [-21.72650794],
       [-13.47767836],
       [-15.26404001],
       [-13.98837797],
       [-13.87764645],
       [-14.2802912 ],
       [-19.5003014 ],
       [-20.5908312 ],
       [-21.59083484],
       [-25.29082005],
       [-31.98519863],
       [-36.0852019 ],
       [-27.22990964],
       [-25.92495708],
       [-25

In [97]:
grad_weights = np.zeros((len(grad_outputs), 16, 1))
def backward(inputs,grad_outputs,batch_size):
    for i in np.arange(batch_size):
        grad_weights[i,:] = np.tile(inputs[i,:], (1, 1)).T.dot(np.tile(grad_outputs[i, :], (1, 1)))
        
    return grad_weights

In [98]:
output_hidden_to_output

array([[-0.72044781],
       [-1.09056908],
       [-1.09055722],
       [-1.09056942],
       [-1.09056943],
       [-1.09056943],
       [-0.59119304],
       [-0.69232122],
       [-0.71446935],
       [-0.70364278],
       [-0.70785129],
       [-0.60155034],
       [-0.590977  ],
       [-0.59090752],
       [-0.72143832],
       [-0.59086866],
       [-0.59091133],
       [-0.68698545],
       [-0.86753201],
       [-0.59395974],
       [-0.77199189],
       [-0.67214586],
       [-0.67940502],
       [-0.71582102],
       [-0.6962535 ],
       [-0.77777907],
       [-0.75865435],
       [-0.77777792],
       [-0.71501039],
       [-0.72650794],
       [-0.77767836],
       [-0.76404001],
       [-0.78837797],
       [-0.77764645],
       [-0.7802912 ],
       [-0.6003014 ],
       [-0.5908312 ],
       [-0.59083484],
       [-0.59082005],
       [-1.18519863],
       [-1.1852019 ],
       [-0.62990964],
       [-0.62495708],
       [-0.80890205],
       [-1.089476  ],
       [-1

In [99]:
grad_hidden_to_output = backward(output_hidden_to_output,grad_outputs,len(grad_outputs))

In [101]:
grad_hidden_to_output.shape

(506, 16, 1)

In [29]:
def update(grad_weights,weights,update_function):
    grad_weights_average = np.mean(grad_weights, 0)
    weights = update_function(weights,grad_weights_average)
    return weights

In [30]:
# 梯度下降法
def batch_gradient_descent(weights, grad_weights):  
    lr = 0.001
    weights_now = weights + lr * grad_weights
    return weights_now

In [31]:
weights_hidden_to_output_new = update(grad_hidden_to_output,weights_hidden_to_output,batch_gradient_descent)

In [33]:
weights_hidden_to_output_new.reshape(-1)

array([ 0.07070002, -0.35480579, -0.05962447,  0.16788701, -0.37981698,
        0.25069673, -0.57178228,  0.17528706, -0.27925468,  0.24480724,
        0.09595551,  0.23322323, -0.33232044,  0.42877296, -0.09034356,
       -0.1885033 ])

In [34]:
grad_hidden_output = grad_outputs.dot(weights_hidden_to_output.T)

In [36]:
grad_hidden_output

array([[ -1.87047692,   8.49418743,   1.30402641,  -4.23780181,
          9.10342132,  -6.25491878,  13.77939947,  -4.41805563,
          6.65387901,  -6.11145987,  -2.48566161,  -5.82929128,
          7.946479  , -10.59258064,   2.05229586,   4.44331552]])

In [37]:
def der_sigmoid(x):
    return sigmoid(x) * (1 - sigmoid(x))

In [39]:
grad_simoid_inputs = grad_hidden_output*der_sigmoid(output_hidden_to_output)

In [40]:
grad_simoid_inputs

array([[-0.46761923,  2.12354686,  0.3260066 , -1.05945045,  2.27585533,
        -1.5637297 ,  3.44484987, -0.86864246,  1.30823201, -1.52786497,
        -0.6214154 , -1.45732282,  1.98661975, -2.64814516,  0.40350586,
         0.87360885]])

In [41]:
grad_input_to_hidden = backward(outputs_input_to_hidden,grad_simoid_inputs)

In [43]:
weights_input_to_hidden_new = update(grad_input_to_hidden,weights_input_to_hidden,batch_gradient_descent)

In [44]:
weights_input_to_hidden_new

array([[-0.30869138, -0.36365895,  0.41273301, -0.10332444, -0.42570369,
         0.3565688 ,  0.12870381, -0.14816078, -0.14102841, -0.27617893,
        -0.09429246,  0.43725663,  0.01155555,  0.33841246, -0.01513624,
        -0.1320727 ],
       [ 0.01126416, -0.05446262,  0.35645225, -0.08239109, -0.2666968 ,
         0.53130775,  0.09750704,  0.22560708,  0.32399666,  0.19735464,
        -0.28575477,  0.06157891,  0.21231716, -0.11248171, -0.43840381,
        -0.2382428 ],
       [ 0.24423992, -0.28423604, -0.41739189, -0.31646319,  0.16640596,
         0.53469557, -0.50095401,  0.30239648, -0.01849383, -0.16899224,
        -0.35190935, -0.09046623, -0.44549153,  0.43186524, -0.00540715,
         0.06518796],
       [-0.1754075 ,  0.28239922,  0.07570541,  0.09208882, -0.41453816,
        -0.12403823, -0.55702845, -0.06040721,  0.28948081,  0.07719998,
         0.45241469, -0.02009017, -0.05459301, -0.03366673,  0.14814532,
         0.09463739],
       [ 0.46563392, -0.04738364, -0

In [ ]:
def softmaxwithloss(inputs, label):
    temp1 = np.exp(inputs)
    probability = temp1 / (np.tile(np.sum(temp1, 1), (inputs.shape[1], 1))).T
    temp3 = np.argmax(label, 1)   #纵坐标
    temp4 = [probability[i, j] for (i, j) in zip(np.arange(label.shape[0]), temp3)]
    loss = -1 * np.mean(np.log(temp4))
    return loss
def der_softmaxwithloss(inputs, label):
    temp1 = np.exp(inputs)
    temp2 = np.sum(temp1, 1)  #它得到的是一维的向量;
    probability = temp1 / (np.tile(temp2, (inputs.shape[1], 1))).T
    gradient = probability - label
    return gradient